version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: 
      context: ./php
      dockerfile: Dockerfile
    image: php:7.3-apache
    volumes:
      - ./php/htdocs:/var/www/html
    ports:
      - 80:80
  
  db:
    container_name: db
    image: mariadb:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: database
        MYSQL_PASSWORD: root
    ports:
        - "9906:3306"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - '8080:80'
      restart: always
      environment:
          PMA_HOST: db
      depends_on:
          - db
volumes:
  flutter_app:
    external: false
